"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "id" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  id: {
    // Navbar
    nav_about_us: "Tentang Kami",
    nav_track_cargo: "Lacak Kargo",
    nav_privacy_policy: "Kebijakan Privasi",
    nav_contact_us: "Hubungi Kami!",
    nav_login: "Masuk",

    // Footer
    footer_text: "© 2026 TERBANGIN AJA CARGO JAKARTA",

    // Home / Landing Page (About Us)
    company_badge: "PT Ekspedisi Terbanginaja",
    about_title_pre: "Tentang",
    about_title_post: "Kami",
    about_desc: "PT Ekspedisi Terbanginaja adalah penyedia layanan kargo udara terkemuka yang berfokus pada pengiriman logistik antar pulau dengan tingkat kecepatan, ketepatan, dan keamanan yang tinggi. Lahir dari kebutuhan akan sistem distribusi yang cepat di era modern, kami menggabungkan armada udara yang andal dengan teknologi manajemen muatan digital dan pelacakan real-time. Dari hasil pertanian segar hingga kargo industri skala besar, kami memastikan setiap barang tiba di tujuannya tepat waktu, setiap saat.",
    vision_title: "Visi Kami",
    vision_desc: "Menjadi pelopor solusi logistik kargo udara paling inovatif dan tepercaya di nusantara, menghubungkan setiap potensi ekonomi daerah tanpa batasan jarak.",
    mission_title: "Misi Kami",
    mission_item1_title: "Ketepatan Waktu",
    mission_item1_desc: "Menjamin SLA pengiriman dengan jadwal penerbangan kargo yang disiplin dan kuat.",
    mission_item2_title: "Didorong Teknologi",
    mission_item2_desc: "Menyediakan sistem pelacakan informasi real-time dan manifes digital yang transparan.",
    mission_item3_title: "Integritas Kargo",
    mission_item3_desc: "Menerapkan standar penerbangan tertinggi untuk memastikan barang tiba dalam kondisi sempurna.",
    
    services_badge: "Apa yang Kami Lakukan Terbaik",
    services_title: "Layanan Utama",
    service1_title: "Kargo Udara Prioritas",
    service1_desc: "SLA Terjamin & Ekspres",
    service2_title: "Penanganan Barang Mudah Rusak",
    service2_desc: "Logistik Terkontrol Suhu",
    service3_title: "Pelacakan Terintegrasi",
    service3_desc: "Koordinat GPS Real-Time",

    why_badge: "Mengapa Bermitra dengan Kami",
    why_title: "Mengapa Memilih Kami?",
    why_item1_title: "Manifes Digital Terpusat",
    why_item1_desc: "Tidak ada lagi dokumen yang hilang atau berserakan. Semua data pengirim, kru yang ditugaskan, dan berat detail per item dicatat secara real-time di sistem Terbanginaja.",
    why_item2_title: "Kapasitas Muatan Fleksibel",
    why_item2_desc: "Mampu menampung volume kargo skala ton dengan perhitungan berat & keseimbangan presisi yang dikendalikan oleh Teknisi Kargo Udara berpengalaman dan berlisensi.",
    why_item3_title: "Transparansi Operasional",
    why_item3_desc: "Menampilkan status kargo secara real-time, memberikan ketenangan pikiran dan audit operasional yang aman bagi mitra bisnis ritel maupun korporat.",

    contact_hq_title: "Kantor Pusat",
    contact_hq_desc: "Bandara Internasional Soekarno-Hatta\nCargo Village (CGK) Air Logistics\nGedung Blok A2, Banten, Indonesia",
    contact_ops_title: "Pusat Operasi",
    contact_ops_desc: "Email: operasional@terbanginaja.co.id\nTelepon/WhatsApp: +62 811-0000-888\nPortal Website: ops.terbanginaja.co.id",

    pkg_badge: "Tarif Pengiriman Fleksibel",
    pkg_title: "Layanan Paket",
    pkg1_title: "Pengiriman Domestik",
    pkg2_title: "Pengiriman Antar Pulau",
    pkg3_title: "Pengiriman Internasional",
    pkg_start: "Mulai Dari",

    // Tracking Page
    track_badge: "Radar Wilayah Udara Kargo",
    track_title_pre: "Lacak",
    track_title_post: "Kargo Anda",
    track_subtitle: "Masukkan Manifest ID untuk melacak pengiriman",
    track_placeholder: "Contoh: MNF-2026-001",
    track_btn_now: "TRACK NOW",
    track_btn_loading: "Mencari...",
    track_err_empty: "Masukkan Manifest ID terlebih dahulu!",
    track_err_db: "Gagal terhubung ke database",
    track_err_not_found: "Manifest tidak ditemukan dalam sistem kami.",
    track_placeholder_prompt: "Silakan masukkan Manifest ID untuk melihat status pengiriman.",
    track_result_manifest: "Manifest ID:",
    track_result_status: "Status:",
    track_result_operational: "Operasional:",
    track_result_history: "Riwayat Pelacakan",
    track_result_no_history: "Belum ada riwayat tracking.",
    track_err_card_title: "Pencarian Gagal",
    track_err_card_desc: "Manifest ID yang Anda masukkan tidak terdaftar dalam database kami. Silakan pastikan format yang diinput benar (Contoh: MNF-2026-001) atau hubungi support administrator maskapai.",

    // Contact Us Page
    contact_us_badge: "Hubungi Kami",
    contact_us_title: "KONTAK KAMI",
    contact_us_left_title: "Dukungan Pelanggan & Operasional",
    contact_us_right_title: "Kantor Pusat",

    // Privacy Policy Page
    privacy_badge: "Dokumentasi Hukum",
    privacy_title: "Kebijakan Privasi",
    privacy_toc: "Daftar Isi",
    privacy_updated: "TERAKHIR DIPERBARUI: 12 APRIL 2026",
    privacy_intro: "PT Ekspedisi Terbanginaja (\"Kami\", \"Milik Kami\", atau \"Perusahaan\") berkomitmen untuk melindungi dan menghormati privasi Anda. Kebijakan Privasi ini menjelaskan bagaimana kami mengumpulkan, menggunakan, melindungi, dan membagikan informasi pribadi Anda saat Anda menggunakan situs web, portal operasional, dan layanan kargo udara kami.",
    
    toc_item1: "1. Informasi yang Kami Kumpulkan",
    toc_item2: "2. Bagaimana Kami Menggunakan Informasi",
    toc_item3: "3. Berbagi dengan Pihak Ketiga",
    toc_item4: "4. Keamanan Data",
    toc_item5: "5. Retensi Data",
    toc_item6: "6. Hak Pengguna",
    toc_item7: "7. Perubahan Kebijakan",

    sec1_title: "Informasi yang Kami Kumpulkan",
    sec1_desc: "Untuk menyediakan layanan logistik yang aman dan efisien, kami mengumpulkan beberapa jenis informasi:",
    sec1_card1_title: "Informasi Akun & Kontak",
    sec1_card1_desc: "Nama lengkap, alamat email, nomor telepon, dan kata sandi saat Anda mendaftar atau masuk ke portal kami.",
    sec1_card2_title: "Informasi Pengiriman (Manifes)",
    sec1_card2_desc: "Detail Pengirim dan Penerima, termasuk nama, alamat lengkap, nomor kontak, dan identitas perusahaan.",
    sec1_card3_title: "Detail Kargo",
    sec1_card3_desc: "Deskripsi barang, berat, dimensi, dan kategori kargo (termasuk Kargo Umum, Barang Mudah Rusak, atau Barang Berbahaya).",
    sec1_card4_title: "Data Pembayaran",
    sec1_card4_desc: "Informasi transaksi untuk tujuan penagihan dan administrasi layanan pengiriman.",
    sec1_card5_title: "Data Teknis & Pelacakan",
    sec1_card5_desc: "Alamat IP, tipe perangkat, waktu akses, dan log aktivitas saat Anda menggunakan fitur 'Lacak Kargo'.",

    sec2_title: "Bagaimana Kami Menggunakan Informasi Anda",
    sec2_desc: "Kami menggunakan informasi yang dikumpulkan untuk tujuan operasional dan hukum, termasuk:",
    sec2_bullet1: "Eksekusi Layanan: Memproses pesanan pengiriman kargo untuk rute domestik (antar-pulau dan dalam-pulau) serta rute internasional.",
    sec2_bullet2: "Manajemen Operasional: Menyiapkan manifes penerbangan, menghitung Berat & Keseimbangan pesawat, dan memberikan instruksi penanganan khusus untuk kru penerbangan dan operator darat.",
    sec2_bullet3: "Pelacakan & Komunikasi: Menyediakan pembaruan status kargo real-time kepada pelanggan dan merespons pertanyaan layanan pelanggan.",
    sec2_bullet4: "Keamanan & Kepatuhan Hukum: Menjamin keselamatan penerbangan, mencegah penipuan, dan mematuhi peraturan penerbangan sipil serta persyaratan bea cukai.",

    sec3_title: "Berbagi dengan Pihak Ketiga",
    sec3_desc: "Kami tidak menjual atau menyewakan data pribadi Anda. Kami hanya membagikan informasi dengan pihak ketiga resmi yang relevan dengan operasi kargo:",
    sec3_bullet1: "Otoritas Bandara & Maskapai: Data manifes dibagikan dengan otoritas bandara dan Insinyur Penerbangan untuk izin penerbangan dan tujuan keselamatan.",
    sec3_bullet2: "Otoritas Hukum & Bea Cukai: Untuk pengiriman internasional, informasi kargo dan identitas pengirim/penerima wajib dilaporkan ke Bea Cukai di negara asal dan tujuan sesuai hukum internasional.",
    sec3_bullet3: "Mitra Logistik Darat: Pihak ketiga yang membantu proses pemuatan/pembongkaran atau pengiriman jarak terakhir (last-mile).",

    sec4_title: "Keamanan Data",
    sec4_desc: "Kami menerapkan standar keamanan teknis dan organisasi yang ketat untuk melindungi data manifes digital dan informasi pribadi Anda dari akses, penggunaan, atau pengungkapan yang tidak sah. Sistem kami menggunakan enkripsi data dan kontrol akses berbasis peran (misalnya, hanya Operator dan Supervisor resmi yang dapat mengubah status kargo).",

    sec5_title: "Retensi Data",
    sec5_desc: "Kami akan menyimpan data pribadi dan riwayat pengiriman Anda selama diperlukan untuk memenuhi tujuan layanan operasional kami, atau sebagaimana diharuskan oleh undang-undang perpajakan yang berlaku dan peraturan penerbangan sipil.",

    sec6_title: "Hak Pengguna",
    sec6_desc: "Anda memiliki hak untuk:",
    sec6_bullet1: "Mengakses dan meninjau informasi profil yang kami simpan tentang Anda.",
    sec6_bullet2: "Meminta koreksi atau pembaruan pada data kontak yang tidak akurat.",
    sec6_bullet3: "Menghubungi layanan pelanggan kami terkait pengelolaan data kargo Anda.",
    
    sec7_title: "Perubahan pada Kebijakan Privasi",
    sec7_desc: "Kami dapat memperbarui Kebijakan Privasi ini dari waktu ke waktu untuk mematuhi peraturan hukum atau peningkatan sistem operasional kami. Perubahan akan diumumkan melalui portal web Ekspedisi Terbanginaja.",

    // Dashboard Layout & Sidebar
    db_dashboard: "Dashboard",
    db_operational: "Operasional",
    db_flight_status: "Status Penerbangan",
    db_tracking_awb: "Pelacakan AWB",
    db_help_desk: "Pusat Bantuan",
    db_welcome: "Selamat Datang,",
    db_logout: "Keluar",
    db_theme_light: "Ubah ke Mode Terang",
    db_theme_dark: "Ubah ke Mode Gelap",
    db_auth_required: "Autentikasi Diperlukan",
    db_login_first: "Silakan Login Terlebih Dahulu",
    db_login_first_desc: "Untuk mengakses halaman operasional kargo, radar penerbangan, dan logistik, silakan masuk ke akun Anda terlebih dahulu.",
    db_login_btn: "Masuk ke Halaman Login",
    db_redirecting: "Mengarahkan otomatis dalam 2.5 detik...",
    db_airport: "BANDARA SOEDIRMAN (CGK)",

    // Help Desk Page
    hd_toast_success: "Tiket {id} dikirim dengan prioritas {priority}!",
    hd_toast_required: "Judul dan deskripsi wajib diisi!",
    hd_title: "Buka Tiket Bantuan Baru",
    hd_desc: "Kirim kendala teknis atau permintaan peralatan kepada Tim IT Support Bandara",
    hd_sub_title: "Subjek / Judul Kendala",
    hd_sub_placeholder: "Contoh: Koneksi Scanner Barcode Warehouse B Terputus",
    hd_cat_title: "Kategori Masalah",
    hd_det_title: "Detail Rincian Kendala",
    hd_det_placeholder: "Jelaskan secara detail kronologi masalah, manifest kargo terdampak, atau lokasi fisik alat yang bermasalah...",
    hd_btn_submit: "Kirim Tiket Bantuan",
    hd_btn_submitting: "Mengirim Tiket...",
    hd_history_title: "Histori Tiket Bantuan Anda",
    hd_history_desc: "Daftar permintaan bantuan yang Anda buka",
    hd_urgency: "Urgensi:",
    hd_empty_tickets: "Belum ada tiket bantuan yang dibuka",
    hd_faq_title: "Tanya Jawab Kendala Umum (FAQ)",
    hd_faq_desc: "Tanya jawab umum & dokumentasi SOP",
    
    // Help Desk Page Error Handling Simulation
    hd_offline_mode: "Simulasi Offline / Gangguan Server",
    hd_offline_active: "Mode Offline Aktif",
    hd_offline_inactive: "Server Normal",
    hd_error_offline_title: "Kesalahan Koneksi Server",
    hd_error_offline_desc: "Koneksi ke server IT Helpdesk terputus (ERR_CONNECTION_REFUSED). Silakan matikan Mode Offline atau hubungi administrator jaringan bandara.",
    hd_error_title_min: "Judul kendala terlalu pendek (minimal 5 karakter).",
    hd_error_desc_min: "Deskripsi kendala terlalu pendek (minimal 15 karakter).",
    hd_error_spam: "Deteksi spam: Deskripsi tidak boleh mengulang kata yang sama terus-menerus.",
    hd_error_category_select: "Silakan pilih kategori masalah yang valid.",
    hd_retry: "Coba Lagi",
    hd_clear_error: "Sembunyikan Pesan Kesalahan",

    // FAQ items translations
    faq_q1: "Bagaimana cara melacak manifes kargo yang tidak ditemukan?",
    faq_a1: "Pastikan format ID manifes sudah benar (Contoh: MNF-2026-001). Jika format sudah benar tetapi masih muncul 'TIDAK DITEMUKAN', periksa apakah data kargo sudah dimasukkan oleh maskapai ke dalam database. Jika belum, Anda dapat membuka tiket kendala AWB di sini.",
    faq_q2: "Bagaimana cara mengubah status operasional penerbangan?",
    faq_a2: "Buka halaman 'Operasional', cari ID manifes kargo yang ingin diubah, lalu klik baris kargo untuk membuka form edit. Di sana Anda dapat memperbarui status penerbangan (Scheduled, Airborne, Landed, Delayed) dan status operasional (In Transit, Completed).",
    faq_q3: "Siapa yang harus dihubungi jika terjadi keadaan darurat IT?",
    faq_a3: "Anda dapat mengirimkan tiket dengan tingkat prioritas 'High' untuk mendapatkan respons cepat dalam waktu 15 menit dari tim IT Shift Bandara Soedirman.",

    // Checkpoint Form & History Translations
    cp_title: "Tambah Checkpoint Baru",
    cp_loc_title: "Lokasi Checkpoint",
    cp_loc_placeholder: "Contoh: Area Sortir CGK",
    cp_desc_title: "Deskripsi / Aktivitas",
    cp_desc_placeholder: "Contoh: Dokumen manifestasi kargo diproses",
    cp_btn_save: "Simpan Checkpoint",
    cp_btn_saving: "Menyimpan...",
    cp_history_title: "RIWAYAT PELACAKAN CHECKPOINT",
    cp_history_loading: "Memuat riwayat pelacakan...",
    cp_history_empty: "Belum ada riwayat pelacakan untuk kargo ini.",
    cp_err_required: "Lokasi dan deskripsi wajib diisi!",
    cp_err_loc_min: "Lokasi checkpoint minimal 3 karakter.",
    cp_err_desc_min: "Deskripsi checkpoint minimal 5 karakter.",
    cp_success: "Checkpoint pelacakan berhasil ditambahkan!",
    cp_err_db: "Gagal menambahkan checkpoint.",
    cp_err_conn: "Terjadi kesalahan koneksi saat menyimpan checkpoint.",
    cp_prompt: "Silakan masukkan Manifest ID di atas untuk melacak atau menambahkan log checkpoint baru.",
    
    // Profile Modal
    profile_modal_title: "Profil Pengguna & Pengaturan",
    profile_name: "Nama Lengkap",
    profile_username: "Username",
    profile_email: "Email",
    profile_department: "Departemen",
    profile_operator_id: "ID Operator",
    profile_language: "Bahasa",
    profile_theme: "Tema",
    profile_close: "Tutup",
    
    // Flight Status Page
    fs_title: "Jadwal Penerbangan Kargo Langsung - Hub CGK",
    fs_desc: "Koneksi Real-time: Database Cloud Neon",
    fs_feed_active: "Umpan Logistik Aktif",
    fs_table_flight: "Nomor Penerbangan",
    fs_table_airline: "Maskapai",
    fs_table_route: "Rute",
    fs_table_scheduled: "Terjadwal",
    fs_table_actual: "Aktual",
    fs_table_gate: "Gerbang",
    fs_table_items: "Item Kargo",
    fs_table_status: "Status",
    fs_no_records: "Tidak ada jadwal penerbangan aktif yang ditemukan di database cloud Neon.",
    fs_showing: "Menampilkan",
    fs_to: "sampai",
    fs_of: "dari",
    fs_flights: "penerbangan",
    fs_securing_conn: "Mengamankan Koneksi",
    fs_syncing: "Sinkronisasi GPS penerbangan kargo dari database Neon...",
    fs_sync_failed: "Sinkronisasi Database Gagal",
    fs_handshake_err: "Tidak dapat menyelesaikan jabat tangan dengan kluster Neon cloud Postgres Singapura.",
    fs_retry: "Coba Hubungkan Kembali",

    // Dashboard Main Page
    db_main_volume_trend: "Tren Volume Kargo Harian",
    db_main_volume_trend_desc: "Kargo diterima, diproses, dan diberangkatkan",
    db_main_on_time_performance: "Ketepatan Waktu Penerbangan",
    db_main_on_time_performance_desc: "Perbandingan bulanan ketepatan waktu penerbangan",
    db_main_incoming_cargo: "Kargo Masuk Hari Ini",
    db_main_incoming_cargo_desc: "Integrasi catatan real-time Neon Postgres",
    db_main_export_btn: "Ekspor",
    db_main_summary: "Ringkasan Kargo Hari Ini",
    db_main_total_active: "Total Catatan Aktif",
    db_main_processed: "Diproses",
    db_main_flight_counter: "Penghitung Status Penerbangan",
    db_main_status_landed: "Mendarat",
    db_main_status_delayed: "Terlambat",
    db_main_status_airborne: "Mengudara",
    db_main_table_awb: "AWB / Manifes",
    db_main_table_airline: "Maskapai",
    db_main_table_route: "Rute",
    db_main_table_weight: "Berat",
    db_main_table_status: "Status Terkini",
    db_main_table_date: "Tanggal Keberangkatan",
    db_main_loading_title: "Membangun Koneksi Cloud",
    db_main_loading_desc: "Mengamankan koneksi & mengunduh manifes real-time...",
    db_main_securing_conn: "Mengamankan Koneksi",
    db_main_syncing: "Menyingkronkan GPS penerbangan kargo dari database Neon...",
    db_main_sync_failed: "Sinkronisasi Database Gagal",
    db_main_handshake_err: "Tidak dapat menyelesaikan jabat tangan dengan kluster Neon cloud Postgres Singapura.",
    db_main_retry: "Coba Hubungkan Kembali",

    // Radar Map
    radar_title: "Pelacak GPS Wilayah Udara Kargo",
    radar_desc: "Pelacakan Armada Aktif | GPS Real-time",
    radar_filter_all: "Semua Kargo",
    radar_filter_en_route: "Dalam Perjalanan",
    radar_filter_arrived: "Tiba",
    radar_search_placeholder: "Cari Kode Target / Rute...",
    radar_gps_status: "STATUS GPS RADAR: AKTIF | MANIFES TERPELACAK:",
    radar_freight_gateway: "GERBANG FREIGHT CGK 3",
    radar_fleet_monitor: "PANTAU ARMADA KARGO",
    radar_gps_nominal: "GPS Nominal",
    radar_tracked: "TERPELACAK",
    radar_en_route: "DALAM PERJALANAN",
    radar_arrived: "TIBA",
    radar_vehicle_title: "KENDARAAN PENGIRIMAN PAKET",
    radar_speed: "KECEPATAN (SPD)",
    radar_speed_knots: "knot",
    radar_speed_arrived: "0 knot (Tiba)",
    radar_altitude: "KETINGGIAN (ALT)",
    radar_alt_ft: "kaki",
    radar_alt_ground: "Terminal Darat",
    radar_gps_coords: "KOORDINAT GPS",
    radar_cargo_load: "MUATAN KARGO",
    radar_load_units: "unit paket",
    radar_manifest_profile: "PROFIL MANIFES KARGO",
    radar_manifest_id: "ID MANIFES",
    radar_cargo_category: "KATEGORI KARGO",
    radar_handling_spec: "SPESIFIKASI PENANGANAN",
    radar_handling_express: "PRIORITAS EKSPRES UDARA",
    radar_handling_standard: "LOGISTIK STANDAR",
    radar_logistics_hub: "HUB LOGISTIK",
    radar_dispatch_gate: "GERBANG DISPATCH",
    radar_standby_title: "SIAGA - MEMINDAI ARMADA KARGO",
    radar_standby_desc: "Klik siluet penerbangan kargo interaktif apa pun pada kisi peta untuk mencegat log pelacakan manifes pengiriman dan rincian muatan paket.",
    radar_live_logs: "LOG HUB LOGISTIK LANGSUNG",
    radar_tips: "Tips Interaktif: Arahkan kursor ke setiap bilah grafik di bawah ini untuk melihat detail data secara instan.",
    radar_chart_center: "Pusat Informasi Analisis & Grafik Real-time",
    radar_neon_connected: "Neon DB Terhubung",
    radar_chart_desc: "Sistem menyajikan 2 grafik analisis yang terintegrasi langsung dengan data kargo aktif:",
    radar_chart1_title: "1. Grafik Tren Volume Kargo Harian",
    radar_chart1_desc: "Menampilkan status operasional kargo yang termasuk dalam manifes.",
    radar_chart2_title: "2. Grafik Kinerja Ketepatan Waktu Penerbangan",
    radar_chart2_desc: "Mengukur rasio keberangkatan dan pendaratan tepat waktu dari penerbangan kargo.",

    // Operational Page
    op_title: "Manajemen Kargo Operasional",
    op_search_placeholder: "Cari ID Manifes / Maskapai / Rute...",
    op_export: "Ekspor",
    op_add_cargo: "+ Tambah Kargo",
    op_edit_title: "⚡ Edit Manifes Kargo",
    op_add_title: "📦 Tambah Kargo Baru",
    op_manifest_id: "ID Manifes (Auto)",
    op_airline_name: "Nama Maskapai *",
    op_select_airline: "-- Pilih Maskapai --",
    op_flight_code: "Kode Penerbangan *",
    op_select_airline_first: "-- Pilih Maskapai Terlebih Dahulu --",
    op_select_flight_code: "-- Pilih Kode Penerbangan --",
    op_flight_route: "Rute Penerbangan (Asal ➔ Tujuan) *",
    op_select_origin: "-- Pilih Asal --",
    op_select_destination: "-- Pilih Tujuan --",
    op_weight: "Berat (kg) *",
    op_date: "Tanggal Pengiriman *",
    op_gate: "Gerbang (Opsional)",
    op_quantity: "Jumlah / Kapasitas (unit) *",
    op_sender_name: "Nama Pengirim *",
    op_receiver_name: "Nama Penerima *",
    op_phone_number: "Nomor Telepon *",
    op_origin_city: "Kota Asal *",
    op_destination_city: "Kota Tujuan *",
    op_item_type: "Jenis Barang *",
    op_shipping_price: "Biaya Pengiriman (Auto)",
    op_shipping_type: "Jenis Pengiriman *",
    op_flight_status: "Status Penerbangan *",
    op_operational_status: "Status Operasional *",
    op_description: "Deskripsi Barang (Opsional)",
    op_cancel: "Batal",
    op_save: "Simpan Kargo",
    op_saving: "Menyimpan...",
    op_no_records: "Tidak ada data kargo yang cocok dengan kriteria pencarian.",
    op_edit: "Ubah",
    op_delete: "Hapus",
    op_manifest_details: "Detail Manifes",
    op_close: "Tutup",
    op_cargo_checkpoints: "Riwayat Pos Pemeriksaan Kargo",
    op_tracking_checkpoint: "Riwayat Pelacakan Pos Pemeriksaan",
    op_location: "Lokasi",
    op_activity: "Aktivitas / Deskripsi",
    op_save_checkpoint: "Simpan Pos Pemeriksaan",
    op_saving_checkpoint: "Menyimpan...",
    err_404_title: "Halaman Tidak Ditemukan",
    err_404_desc: "Halaman yang Anda tuju tidak tersedia atau Anda belum melakukan login ke dalam sistem.",
    err_404_btn: "Masuk / Kembali ke Dashboard",
  },
  en: {
    // Navbar
    nav_about_us: "About Us",
    nav_track_cargo: "Track Your Cargo",
    nav_privacy_policy: "Privacy Policy",
    nav_contact_us: "Contact Us!",
    nav_login: "Login",

    // Footer
    footer_text: "© 2026 TERBANGIN AJA CARGO JAKARTA",

    // Home / Landing Page (About Us)
    company_badge: "PT Ekspedisi Terbanginaja",
    about_title_pre: "About",
    about_title_post: "Us",
    about_desc: "PT Ekspedisi Terbanginaja is a leading air freight service provider focused on inter-island logistics delivery with high-level speed, precision, and security. Born from the need for rapid distribution systems in the modern era, we combine a reliable air fleet with digital payload management and tracking technology. From fresh agricultural produce to large-scale industrial cargo, we ensure every item arrives at its destination on time, every time.",
    vision_title: "Our Vision",
    vision_desc: "To be the pioneer of the most innovative and trusted air cargo logistics solutions in the archipelago, connecting every regional economic potential without distance barriers.",
    mission_title: "Our Mission",
    mission_item1_title: "Punctuality",
    mission_item1_desc: "Guaranteeing delivery SLAs with disciplined and robust cargo flight schedules.",
    mission_item2_title: "Technology Driven",
    mission_item2_desc: "Providing real-time information tracking systems and transparent digital manifests.",
    mission_item3_title: "Cargo Integrity",
    mission_item3_desc: "Applying the highest aviation standards to ensure goods arrive in perfect condition.",
    
    services_badge: "What We Do Best",
    services_title: "Core Services",
    service1_title: "Priority Air Freight",
    service1_desc: "SLA-Guaranteed Express",
    service2_title: "Perishable Goods Handling",
    service2_desc: "Temperature-Controlled Logistics",
    service3_title: "Integrated Tracking",
    service3_desc: "Real-time GPS coordinates",

    why_badge: "Why Partner With Us",
    why_title: "Why Choose Us?",
    why_item1_title: "Centralized Digital Manifest",
    why_item1_desc: "No more lost or scattered paperwork. All shipper data, assigned crew, and detailed weight per item are recorded in real-time within the Ekspedisi Terbanginaja system.",
    why_item2_title: "Flexible Payload Capacity",
    why_item2_desc: "Capable of accommodating ton-scale cargo volumes with precise weight & balance calculations controlled by experienced and licensed Air Cargo Engineers.",
    why_item3_title: "Operational Transparency",
    why_item3_desc: "Displaying the real-time status of cargo, providing complete peace of mind and secure operational auditing for retail and corporate business partners.",

    contact_hq_title: "Headquarters",
    contact_hq_desc: "Soekarno-Hatta International Airport\nCargo Village (CGK) Air Logistics\nBuilding Block A2, Banten, Indonesia",
    contact_ops_title: "Ops Center",
    contact_ops_desc: "Email: operasional@terbanginaja.co.id\nPhone/WhatsApp: +62 811-0000-888\nWebsite Portal: ops.terbanginaja.co.id",

    pkg_badge: "Flexible Shipping Rates",
    pkg_title: "Package Services",
    pkg1_title: "Domestic Island Delivery",
    pkg2_title: "Delivery to other islands",
    pkg3_title: "International Shipping",
    pkg_start: "Start From",

    // Tracking Page
    track_badge: "Cargo Airspace Radar",
    track_title_pre: "Track",
    track_title_post: "Your Cargo",
    track_subtitle: "Enter Manifest ID to track shipment",
    track_placeholder: "Example: MNF-2026-001",
    track_btn_now: "TRACK NOW",
    track_btn_loading: "Searching...",
    track_err_empty: "Please enter Manifest ID first!",
    track_err_db: "Failed to connect to database",
    track_err_not_found: "Manifest not found in our system.",
    track_placeholder_prompt: "Please enter Manifest ID to see shipping status.",
    track_result_manifest: "Manifest ID:",
    track_result_status: "Status:",
    track_result_operational: "Operational:",
    track_result_history: "Tracking History",
    track_result_no_history: "No tracking history yet.",
    track_err_card_title: "Search Failed",
    track_err_card_desc: "The Manifest ID you entered is not registered in our database. Please make sure the format entered is correct (Example: MNF-2026-001) or contact the airline support administrator.",

    // Contact Us Page
    contact_us_badge: "Get in Touch",
    contact_us_title: "OUR CONTACT",
    contact_us_left_title: "Customer & Operational Support",
    contact_us_right_title: "Head Office",

    // Privacy Policy Page
    privacy_badge: "Legal Documentation",
    privacy_title: "Privacy Policy",
    privacy_toc: "Table of Contents",
    privacy_updated: "LAST UPDATED: APRIL 12, 2026",
    privacy_intro: "PT Ekspedisi Terbanginaja (\"We\", \"Our\", or \"The Company\") is committed to protecting and respecting your privacy. This Privacy Policy explains how we collect, use, protect, and share your personal information when you use our website, operational portal, and air cargo services.",
    
    toc_item1: "1. Information We Collect",
    toc_item2: "2. How We Use Information",
    toc_item3: "3. Sharing with Third Parties",
    toc_item4: "4. Data Security",
    toc_item5: "5. Data Retention",
    toc_item6: "6. User Rights",
    toc_item7: "7. Policy Changes",

    sec1_title: "Information We Collect",
    sec1_desc: "To provide safe and efficient logistics services, we collect several types of information:",
    sec1_card1_title: "Account & Contact Information",
    sec1_card1_desc: "Full name, email address, phone number, and password when you register or log in to our portal.",
    sec1_card2_title: "Shipment Information (Manifest)",
    sec1_card2_desc: "Details of the Shipper and Consignee, including names, full addresses, contact numbers, and corporate identities.",
    sec1_card3_title: "Cargo Details",
    sec1_card3_desc: "Item descriptions, weight, dimensions, and cargo categories (including General Cargo, Perishable Goods, or Dangerous Goods).",
    sec1_card4_title: "Payment Data",
    sec1_card4_desc: "Transaction information for billing purposes and administration of shipping services.",
    sec1_card5_title: "Technical & Tracking Data",
    sec1_card5_desc: "IP addresses, device types, access times, and activity logs when you use the 'Track Your Cargo' feature.",

    sec2_title: "How We Use Your Information",
    sec2_desc: "We use the collected information for operational and legal purposes, including:",
    sec2_bullet1: "Service Execution: Processing cargo shipment orders for domestic (inter-island and intra-island) and international routes.",
    sec2_bullet2: "Operational Management: Preparing flight manifests, calculating aircraft Weight & Balance, and providing special handling instructions for flight crews and ground operators.",
    sec2_bullet3: "Tracking & Communication: Providing real-time cargo status updates to customers and responding to customer service inquiries.",
    sec2_bullet4: "Security & Legal Compliance: Ensuring aviation safety, preventing fraud, and complying with civil aviation regulations and customs requirements.",

    sec3_title: "Sharing with Third Parties",
    sec3_desc: "We do not sell or rent your personal data. We only share information with authorized third parties relevant to cargo operations:",
    sec3_bullet1: "Airport Authorities & Airlines: Manifest data is shared with airport authorities and Air Engineers for flight permits and safety purposes.",
    sec3_bullet2: "Legal & Customs Authorities: For international shipments, cargo information and shipper/consignee identities must be reported to Customs in the origin and destination countries in accordance with international law.",
    sec3_bullet3: "Ground Logistics Partners: Third parties that assist in the loading/unloading process or last-mile delivery.",

    sec4_title: "Data Security",
    sec4_desc: "We implement strict technical and organizational security standards to protect your digital manifest data and personal information from unauthorized access, use, or disclosure. Our system utilizes data encryption and role-based access control (e.g., only authorized Operators and Supervisors can modify cargo status).",

    sec5_title: "Data Retention",
    sec5_desc: "We will store your personal data and shipment history for as long as necessary to fulfill our operational service goals, or as required by applicable tax laws and civil aviation regulations.",

    sec6_title: "User Rights",
    sec6_desc: "You have the right to:",
    sec6_bullet1: "Access and review the profile information we store about you.",
    sec6_bullet2: "Request corrections or updates to inaccurate contact data.",
    sec6_bullet3: "Contact our customer service regarding the management of your cargo data.",
    
    sec7_title: "Changes to the Privacy Policy",
    sec7_desc: "We may update this Privacy Policy from time to time to comply with legal regulations or improvements to our operational systems. Changes will be announced through the Ekspedisi Terbanginaja web portal.",

    // Dashboard Layout & Sidebar
    db_dashboard: "Dashboard",
    db_operational: "Operational",
    db_flight_status: "Flight Status",
    db_tracking_awb: "Tracking AWB",
    db_help_desk: "Help Desk",
    db_welcome: "Welcome,",
    db_logout: "Log Out",
    db_theme_light: "Switch to Light Mode",
    db_theme_dark: "Switch to Dark Mode",
    db_auth_required: "Authentication Required",
    db_login_first: "Please Login First",
    db_login_first_desc: "To access the cargo operations, flight radar, and logistics pages, please log in to your account first.",
    db_login_btn: "Go to Login Page",
    db_redirecting: "Redirecting automatically in 2.5 seconds...",
    db_airport: "SOEDIRMAN AIRPORT (CGK)",

    // Help Desk Page
    hd_toast_success: "Ticket {id} submitted with {priority} priority!",
    hd_toast_required: "Subject and description are required!",
    hd_title: "Open a New Support Ticket",
    hd_desc: "Submit technical issues or equipment requests to the Airport IT Support Team",
    hd_sub_title: "Subject / Issue Title",
    hd_sub_placeholder: "Example: Warehouse B Barcode Scanner Connection Disconnected",
    hd_cat_title: "Problem Category",
    hd_det_title: "Detailed Issue Description",
    hd_det_placeholder: "Describe in detail the timeline of the issue, affected cargo manifest, or physical location of the malfunctioning equipment...",
    hd_btn_submit: "Submit Support Ticket",
    hd_btn_submitting: "Submitting Ticket...",
    hd_history_title: "Your Support Ticket History",
    hd_history_desc: "List of support requests opened by you",
    hd_urgency: "Urgency:",
    hd_empty_tickets: "No support tickets opened yet",
    hd_faq_title: "Frequently Asked Questions (FAQ)",
    hd_faq_desc: "Frequently asked questions & SOP documentation",

    // Help Desk Page Error Handling Simulation
    hd_offline_mode: "Simulate Offline / Server Outage",
    hd_offline_active: "Offline Mode Active",
    hd_offline_inactive: "Server Normal",
    hd_error_offline_title: "Server Connection Error",
    hd_error_offline_desc: "Connection to IT Helpdesk server lost (ERR_CONNECTION_REFUSED). Please turn off Offline Mode or contact the airport network administrator.",
    hd_error_title_min: "Issue subject is too short (minimum 5 characters).",
    hd_error_desc_min: "Issue description is too short (minimum 15 characters).",
    hd_error_spam: "Spam detected: Description cannot repeatedly reuse the same word.",
    hd_error_category_select: "Please select a valid problem category.",
    hd_retry: "Retry",
    hd_clear_error: "Hide Error Message",

    // FAQ items translations
    faq_q1: "How to track a cargo manifest that is not found?",
    faq_a1: "Make sure the manifest ID format is correct (Example: MNF-2026-001). If the format is correct but 'NOT FOUND' still appears, check if the cargo data has been entered by the airline in the database. If not, you can open an AWB issue ticket here.",
    faq_q2: "How do I change the flight operational status?",
    faq_a2: "Go to the 'Operational' page, find the manifest ID of the cargo you want to modify, and click the cargo row to open the edit form. There you can update the flight status (Scheduled, Airborne, Landed, Delayed) and operational status (In Transit, Completed).",
    faq_q3: "Who should be contacted in case of an IT emergency?",
    faq_a3: "You can submit a ticket with a 'High' priority level for a rapid response within 15 minutes from the Soedirman Airport IT Shift team.",

    // Checkpoint Form & History Translations
    cp_title: "ADD NEW CHECKPOINT",
    cp_loc_title: "Checkpoint Location",
    cp_loc_placeholder: "Example: CGK Sorting Area",
    cp_desc_title: "Description / Activity",
    cp_desc_placeholder: "Example: Cargo manifestation documents processed",
    cp_btn_save: "Save Checkpoint",
    cp_btn_saving: "Saving...",
    cp_history_title: "CHECKPOINT TRACKING HISTORY",
    cp_history_loading: "Loading tracking history...",
    cp_history_empty: "No tracking history found for this cargo yet.",
    cp_err_required: "Location and description are required!",
    cp_err_loc_min: "Checkpoint location must be at least 3 characters.",
    cp_err_desc_min: "Checkpoint description must be at least 5 characters.",
    cp_success: "Tracking checkpoint successfully added!",
    cp_err_db: "Failed to add checkpoint.",
    cp_err_conn: "Connection error occurred while saving checkpoint.",
    cp_prompt: "Please enter a Manifest ID above to track or add a new checkpoint log.",
    
    // Profile Modal
    profile_modal_title: "User Profile & Settings",
    profile_name: "Full Name",
    profile_username: "Username",
    profile_email: "Email",
    profile_department: "Department",
    profile_operator_id: "Operator ID",
    profile_language: "Language",
    profile_theme: "Theme",
    profile_close: "Close",
    
    // Flight Status Page
    fs_title: "Live Cargo Flight Schedule - CGK Hub",
    fs_desc: "Realtime Connection: Cloud Neon Database",
    fs_feed_active: "Logistics Feed Active",
    fs_table_flight: "Flight Number",
    fs_table_airline: "Airline",
    fs_table_route: "Route",
    fs_table_scheduled: "Scheduled",
    fs_table_actual: "Actual",
    fs_table_gate: "Gate",
    fs_table_items: "Cargo Items",
    fs_table_status: "Status",
    fs_no_records: "No active flight schedules found in Neon cloud database.",
    fs_showing: "Showing",
    fs_to: "to",
    fs_of: "of",
    fs_flights: "flights",
    fs_securing_conn: "Securing Connection",
    fs_syncing: "Syncing cargo flight GPS from Neon database...",
    fs_sync_failed: "Database Sync Failed",
    fs_handshake_err: "Could not complete handshake with Neon cloud Postgres Singapore cluster.",
    fs_retry: "Retry Connection",

    // Dashboard Main Page
    db_main_volume_trend: "Daily Cargo Volume Trend",
    db_main_volume_trend_desc: "Cargo received, processed, and departed",
    db_main_on_time_performance: "Flight On-Time Performance",
    db_main_on_time_performance_desc: "Monthly comparison of flight punctuality",
    db_main_incoming_cargo: "Today's Incoming Cloud Cargo",
    db_main_incoming_cargo_desc: "Real-time Neon Postgres records integration",
    db_main_export_btn: "Export",
    db_main_summary: "Today's Cargo Summary",
    db_main_total_active: "Total Active Records",
    db_main_processed: "Processed",
    db_main_flight_counter: "Flight Status Counter",
    db_main_status_landed: "Landed",
    db_main_status_delayed: "Delayed",
    db_main_status_airborne: "Airborne",
    db_main_table_awb: "AWB / Manifest",
    db_main_table_airline: "Airline",
    db_main_table_route: "Route",
    db_main_table_weight: "Weight",
    db_main_table_status: "Current Status",
    db_main_table_date: "Departure Date",
    db_main_loading_title: "Establishing Cloud Connection",
    db_main_loading_desc: "Securing connection & downloading real-time manifests...",
    db_main_securing_conn: "Securing Connection",
    db_main_syncing: "Syncing cargo flight GPS from Neon database...",
    db_main_sync_failed: "Database Sync Failed",
    db_main_handshake_err: "Could not complete handshake with Neon cloud Postgres Singapore cluster.",
    db_main_retry: "Retry Connection",

    // Radar Map
    radar_title: "Cargo Airspace GPS Tracker",
    radar_desc: "Fleet Tracking active | Realtime GPS Uplink",
    radar_filter_all: "All Cargo",
    radar_filter_en_route: "En Route",
    radar_filter_arrived: "Arrived",
    radar_search_placeholder: "Search Target Code / Route...",
    radar_gps_status: "RADAR GPS STAT: ACTIVE | MANIFEST TRACKED:",
    radar_freight_gateway: "CGK FREIGHT GATEWAY 3",
    radar_fleet_monitor: "CARGO FLEET MONITOR",
    radar_gps_nominal: "GPS Nominal",
    radar_tracked: "TRACKED",
    radar_en_route: "EN ROUTE",
    radar_arrived: "ARRIVED",
    radar_vehicle_title: "PARCEL SHIPMENT VEHICLE",
    radar_speed: "SPEED (SPD)",
    radar_speed_knots: "knots",
    radar_speed_arrived: "0 kts (Arrived)",
    radar_altitude: "ALTITUDE (ALT)",
    radar_alt_ft: "ft",
    radar_alt_ground: "Ground Terminal",
    radar_gps_coords: "GPS COORDINATES",
    radar_cargo_load: "CARGO LOAD",
    radar_load_units: "parcel units",
    radar_manifest_profile: "CARGO MANIFEST PROFILE",
    radar_manifest_id: "MANIFEST ID",
    radar_cargo_category: "CARGO CATEGORY",
    radar_handling_spec: "HANDLING SPEC",
    radar_handling_express: "PRIORITY AIR EXPRESS",
    radar_handling_standard: "STANDARD LOGISTICS",
    radar_logistics_hub: "LOGISTICS HUB",
    radar_dispatch_gate: "DISPATCH GATE",
    radar_standby_title: "STANDBY - SCANNING CARGO FLEETS",
    radar_standby_desc: "Click on any interactive cargo flight silhouette on the map grid to intercept delivery manifest tracking logs and parcel load details.",
    radar_live_logs: "LIVE LOGISTICS HUB LOGS",
    radar_tips: "Interactive Tips: Hover over each chart bar below to view data details instantly.",
    radar_chart_center: "Real-time Analytics & Chart Information Center",
    radar_neon_connected: "Neon DB Connected",
    radar_chart_desc: "The system presents 2 analytical charts directly integrated with active cargo data:",
    radar_chart1_title: "1. Daily Cargo Volume Trend Chart",
    radar_chart1_desc: "Displays the operational status of cargo included in the manifest.",
    radar_chart2_title: "2. Flight On-Time Performance Chart",
    radar_chart2_desc: "Measures the on-time departure and landing ratio of cargo flights.",

    // Operational Page
    op_title: "Operational Cargo Management",
    op_search_placeholder: "Search Manifest ID / Airline / Route...",
    op_export: "Export",
    op_add_cargo: "+ Add Cargo",
    op_edit_title: "⚡ Edit Cargo Manifest",
    op_add_title: "📦 Add New Cargo",
    op_manifest_id: "Manifest ID (Auto)",
    op_airline_name: "Airline Name *",
    op_select_airline: "-- Select Airline --",
    op_flight_code: "Flight Code *",
    op_select_airline_first: "-- Select Airline First --",
    op_select_flight_code: "-- Select Flight Code --",
    op_flight_route: "Flight Route (Origin ➔ Destination) *",
    op_select_origin: "-- Select Origin --",
    op_select_destination: "-- Select Destination --",
    op_weight: "Weight (kg) *",
    op_date: "Shipping Date *",
    op_gate: "Gate (Optional)",
    op_quantity: "Quantity / Capacity (units) *",
    op_sender_name: "Sender Name *",
    op_receiver_name: "Receiver Name *",
    op_phone_number: "Phone Number *",
    op_origin_city: "Origin City *",
    op_destination_city: "Destination City *",
    op_item_type: "Item Type *",
    op_shipping_price: "Shipping Price (Auto)",
    op_shipping_type: "Shipping Type *",
    op_flight_status: "Flight Status *",
    op_operational_status: "Operational Status *",
    op_description: "Item Description (Optional)",
    op_cancel: "Cancel",
    op_save: "Save Cargo",
    op_saving: "Saving...",
    op_no_records: "No cargo data matches the search criteria.",
    op_edit: "Edit",
    op_delete: "Delete",
    op_manifest_details: "Manifest Details",
    op_close: "Close",
    op_cargo_checkpoints: "Cargo Checkpoints History",
    op_tracking_checkpoint: "Tracking Checkpoint History",
    op_location: "Location",
    op_activity: "Activity / Description",
    op_save_checkpoint: "Save Checkpoint",
    op_saving_checkpoint: "Saving...",
    err_404_title: "Page Not Found",
    err_404_desc: "The page you are looking for is not available or you have not logged into the system.",
    err_404_btn: "Sign In / Return to Dashboard",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("id");

  useEffect(() => {
    const savedLang = localStorage.getItem("language") as Language;
    if (savedLang === "id" || savedLang === "en") {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations["id"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
